spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl

---

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    
